repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-docstrings
          - flake8-modern-annotations
          - flake8-pyproject
          - flake8-pytest-style
          - flake8-quotes
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        name: add trailing comma
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [
          --wrap-summaries=100,
          --wrap-descriptions=0,
          --in-place,
          --blank
        ]


