name: lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check installed dependencies
        run: poetry show

      - name: Install pre-commit hooks
        run: |
          poetry run pre-commit install

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files